"""Add financial health cache model

Revision ID: 2b9ef4897491
Revises: a7d3f1c9b204
Create Date: 2026-07-29 23:52:58.881044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9ef4897491'
down_revision: Union[str, Sequence[str], None] = 'a7d3f1c9b204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_health_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('ai_insights_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_health_cache_id'), 'financial_health_cache', ['id'], unique=False)
    op.create_index(op.f('ix_financial_health_cache_user_id'), 'financial_health_cache', ['user_id'], unique=True)
    op.create_index(op.f('ix_budgets_budget_id'), 'budgets', ['budget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_budget_id'), table_name='budgets')
    op.drop_index(op.f('ix_financial_health_cache_user_id'), table_name='financial_health_cache')
    op.drop_index(op.f('ix_financial_health_cache_id'), table_name='financial_health_cache')
    op.drop_table('financial_health_cache')
    # ### end Alembic commands ###
