from pydantic import BaseModel, Field
from typing import Optional

class AssistantQuery(BaseModel):
    query: str = Field(..., description="The query from the user")

class AssistantResponse(BaseModel):
    answer: str = Field(..., description="The response generated by the AI")
    mode_used: str = Field(..., description="The mode that was actually used to generate the response")
